name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Download Dependencies
        run: |
          go mod download
      - name: Check Formatting & Test
        run: |
          make test
      - name: Build Provider
        run: |
          make build
