name: test
on: push

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.16
#      - name: Configure Go Caches
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cache/go-build
#            ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#      - name: Download Dependencies
#        run: |
#          go mod download
#      - name: Check Formatting & Test
#        run: |
#          make test
#      - name: Build Provider
#        run: |
#          make build
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Configure Go Caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
      - name: Deploy
        run: |
          terraform -chdir=services init
          terraform -chdir=services apply -auto-approve

          kubectl -n rode-tf port-forward svc/rode 50051 &
          trap 'pkill kubectl' EXIT

          make testacc

